Homework5
tomy807/ModernCppCourse pull request #5
Opened 2022-05-22 10:20 UTC by tomy807

1. openCV2 설치후 관련 용어 공부했습니다.
2. jpg파일->cv::Mat->binary file로 Serialize,역으로 Deserialize 하는 과제였습니다.
3. filesystem으로 주소 찾고 fstream 으로 파일을 read,write 했습니다.

2022-05-22 11:03 UTC, AlanSynn requested changes
.gitignore 를 디렉토리마다 관리하는건 안좋은 방식입니다.
한번 .gitignore로 .a 나 .out 파일들 처리 하고 올려주시겠어요?

2022-05-22 11:28 UTC, AlanSynn commented
아 여기에서 .gitignore 정리하라는건 루트에만 하나 두고 관리하라는 뜻이었어요.

2022-05-22 11:30 UTC, AlanSynn commented
그리고 한번 .gitignore 를 수정하면 캐시를 비워야합니다.
https://yongdev91.tistory.com/11

2022-05-22 11:37 UTC, tomy807 commented
PR를 지웠다가 다시 올릴까요?
어떻게 수정하는지 잘 모르겠어서..

2022-05-23 04:38 UTC, AlanSynn approved these changes
LGTM 이정도면 많이 지웠네요.
어떻게 관리하는지 알겠죠?

2022-05-23 04:50 UTC, tomy807 commented
넵! 이제 조금 알거 같아요. 그래도 git은 확실하게 공부 좀 해야할거 같아요..ㅋㅋ

2022-05-23 04:50 UTC, tomy807 commented
> LGTM 이정도면 많이 지웠네요. 어떻게 관리하는지 알겠죠?

2022-05-23 04:50 UTC, closed without merging

2022-05-25 03:06 UTC, AlanSynn commented
이거 머지안하고 그대로 클로즈했네요?

2022-05-25 03:10 UTC, AlanSynn commented
아 로컬에서 머지하셨구나 된거같으니 delete 하세요